2025-05-05 09:33:01.766 WARNING (Recorder) [homeassistant.components.recorder.util] The system could not validate that the sqlite3 database at //config/home-assistant_v2.db was shutdown cleanly
2025-05-05 09:35:02.611 WARNING (MainThread) [homeassistant.bootstrap] Setup timed out for stage 1 waiting on {<Task pending name='platform loaded tts' coro=<async_setup_legacy.<locals>.async_platform_discovered() running at /usr/src/homeassistant/homeassistant/components/tts/legacy.py:194> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/local/lib/python3.13/asyncio/futures.py:384, Task.task_wakeup()]> cb=[set.remove()]>} - moving forward
2025-05-05 09:35:49.380 WARNING (MainThread) [homeassistant.setup] Setup of stream is taking over 10 seconds.
2025-05-05 09:39:28.636 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: {('mqtt', '01JSYF1F4DSP2QG0KHMYH14YT7'): 797.969257582, ('shopping_list', '01JSYC2SN6A67EC2FDVJTZNVF6'): 801.44110292, ('backup', '01JSY9RJ9XA8FP63FK69PSH9DR'): 806.490720617}
2025-05-05 09:39:40.741 ERROR (MainThread) [homeassistant.bootstrap] Error setting up integration dhcp - received exception
asyncio.exceptions.CancelledError
2025-05-05 09:39:40.741 ERROR (MainThread) [homeassistant.bootstrap] Error setting up integration default_config - received exception
asyncio.exceptions.CancelledError
2025-05-05 09:39:40.742 ERROR (MainThread) [homeassistant.bootstrap] Error setting up integration bluetooth - received exception
asyncio.exceptions.CancelledError
2025-05-05 09:39:40.742 ERROR (MainThread) [homeassistant.bootstrap] Error setting up integration ssdp - received exception
asyncio.exceptions.CancelledError
2025-05-05 09:45:02.615 WARNING (MainThread) [homeassistant.components.mqtt.client] Error returned from MQTT server: The connection was lost.
2025-05-05 09:49:04.730 ERROR (MainThread) [homeassistant.components.mqtt.entity] Error 'expected SensorDeviceClass or one of 'date', 'enum', 'timestamp', 'apparent_power', 'aqi', 'area', 'atmospheric_pressure', 'battery', 'blood_glucose_concentration', 'carbon_monoxide', 'carbon_dioxide', 'conductivity', 'current', 'data_rate', 'data_size', 'distance', 'duration', 'energy', 'energy_distance', 'energy_storage', 'frequency', 'gas', 'humidity', 'illuminance', 'irradiance', 'moisture', 'monetary', 'nitrogen_dioxide', 'nitrogen_monoxide', 'nitrous_oxide', 'ozone', 'ph', 'pm1', 'pm10', 'pm25', 'power_factor', 'power', 'precipitation', 'precipitation_intensity', 'pressure', 'reactive_power', 'signal_strength', 'sound_pressure', 'speed', 'sulphur_dioxide', 'temperature', 'volatile_organic_compounds', 'volatile_organic_compounds_parts', 'voltage', 'volume', 'volume_storage', 'volume_flow_rate', 'water', 'weight', 'wind_direction', 'wind_speed' for dictionary value @ data['device_class']' when processing MQTT discovery message topic: 'homeassistant/sensor/cuisine_Temp/config', message: '{'device_class': 'Temp', 'state_topic': 'home/cuisine/esp8266-EC:FA:BC:1A:5D:A8/Temp/state', 'unit_of_measurement': '%', 'unique_id': 'esp8266_EC:FA:BC:1A:5D:A8_Temp', 'name': 'Temp Cuisine'}'
2025-05-05 09:55:19.172 WARNING (MainThread) [homeassistant.components.mqtt.sensor] The unit of measurement `%` is not valid together with device class `temperature`. this will stop working in HA Core 2025.7.0
2025-05-05 10:25:47.258 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.temp_cuisine (<class 'homeassistant.components.mqtt.sensor.MqttSensor'>) is using native unit of measurement '%' which is not a valid unit for the device class ('temperature') it is using; expected one of ['K', '°C', '°F']; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+mqtt%22
2025-05-05 12:17:25.287 WARNING (MainThread) [homeassistant.components.mqtt.client] Error returned from MQTT server: The connection was lost.
